"use client";
import { useEffect, useRef, useState } from "react";

type Level=[number,number];
type Trade={price:number;qty:number;buyerMaker:boolean};
type Frame={bids:Level[];asks:Level[];trades:Trade[];mid:number;time:number};
type Metrics={levels:number;trades:number;frames:number;imbalance:number;spread:number;buyQty:number;sellQty:number;bid:number;ask:number};
const EMPTY_METRICS:Metrics={levels:0,trades:0,frames:0,imbalance:50,spread:0,buyQty:0,sellQty:0,bid:0,ask:0};
const base=(symbol:string)=>symbol.replace("USDT","");
const priceLabel=(n:number)=>n>=1000?n.toLocaleString("en-US",{maximumFractionDigits:2}):n>=1?n.toFixed(3):n.toPrecision(5);
const qtyLabel=(n:number)=>new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(n);

export default function LiveBookmap({symbols}:{symbols:string[]}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const framesRef=useRef<Frame[]>([]);const bookRef=useRef<{bids:Level[];asks:Level[]}>({bids:[],asks:[]});const pendingTradesRef=useRef<Trade[]>([]);const totalsRef=useRef({trades:0,buyQty:0,sellQty:0});
  const [symbol,setSymbol]=useState("BTCUSDT");const [status,setStatus]=useState<"conectando"|"en vivo"|"no disponible">("conectando");const [paused,setPaused]=useState(false);const pausedRef=useRef(false);const [started,setStarted]=useState("");const [metrics,setMetrics]=useState<Metrics>(EMPTY_METRICS);const [ladder,setLadder]=useState<{bids:Level[];asks:Level[]}>({bids:[],asks:[]});
  useEffect(()=>{pausedRef.current=paused},[paused]);
  useEffect(()=>{
    framesRef.current=[];bookRef.current={bids:[],asks:[]};pendingTradesRef.current=[];totalsRef.current={trades:0,buyQty:0,sellQty:0};
    const boot=setTimeout(()=>{setStatus("conectando");setStarted(new Date().toLocaleTimeString());setMetrics(EMPTY_METRICS);setLadder({bids:[],asks:[]})},0);let closed=false,retry:ReturnType<typeof setTimeout>;let watchdog:ReturnType<typeof setTimeout>;const key=symbol.toLowerCase();
    const connect=(host:string)=>{
      const ws=new WebSocket(`${host}/stream?streams=${key}@depth20@100ms/${key}@aggTrade`);let receivedDepth=false;
      watchdog=setTimeout(()=>{if(!receivedDepth)ws.close()},9000);
      ws.onmessage=event=>{try{const message=JSON.parse(event.data);const data=message.data??message;const rawBids=data?.b??data?.bids,rawAsks=data?.a??data?.asks;
        if(Array.isArray(rawBids)&&Array.isArray(rawAsks)){const bids=rawBids.map((x:string[])=>[Number(x[0]),Number(x[1])] as Level).filter(x=>x[0]>0&&x[1]>=0);const asks=rawAsks.map((x:string[])=>[Number(x[0]),Number(x[1])] as Level).filter(x=>x[0]>0&&x[1]>=0);if(bids.length&&asks.length){bookRef.current={bids,asks};receivedDepth=true;setStatus("en vivo")}}
        else if(data?.e==="aggTrade"){const trade={price:Number(data.p),qty:Number(data.q),buyerMaker:Boolean(data.m)};if(trade.price>0&&trade.qty>0){pendingTradesRef.current.push(trade);if(pendingTradesRef.current.length>180)pendingTradesRef.current.shift();totalsRef.current.trades+=1;if(trade.buyerMaker)totalsRef.current.sellQty+=trade.qty;else totalsRef.current.buyQty+=trade.qty}}
      }catch{return}};
      ws.onerror=()=>ws.close();ws.onclose=()=>{clearTimeout(watchdog);if(closed)return;setStatus("conectando");const next=host.includes("stream.binance.com")?"wss://data-stream.binance.vision":"wss://stream.binance.com:9443";retry=setTimeout(()=>connect(next),1200)};return ws;
    };
    const ws=connect("wss://stream.binance.com:9443");
    const capture=setInterval(()=>{if(pausedRef.current)return;const book=bookRef.current;if(!book.bids.length||!book.asks.length)return;const trades=pendingTradesRef.current.splice(0);const bid=book.bids[0][0],ask=book.asks[0][0],mid=(bid+ask)/2;framesRef.current.push({bids:book.bids.map(x=>[...x] as Level),asks:book.asks.map(x=>[...x] as Level),trades,mid,time:Date.now()});if(framesRef.current.length>140)framesRef.current.shift();const bidQty=book.bids.reduce((sum,x)=>sum+x[1],0),askQty=book.asks.reduce((sum,x)=>sum+x[1],0),total=bidQty+askQty;setLadder({bids:book.bids.slice(0,6),asks:book.asks.slice(0,6)});setMetrics({levels:book.bids.length+book.asks.length,trades:totalsRef.current.trades,frames:framesRef.current.length,imbalance:total?bidQty/total*100:50,spread:mid?(ask-bid)/mid*100:0,buyQty:totalsRef.current.buyQty,sellQty:totalsRef.current.sellQty,bid,ask})},500);
    return()=>{closed=true;clearTimeout(boot);clearTimeout(retry);clearTimeout(watchdog);clearInterval(capture);ws.close()};
  },[symbol]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;let animation=0;const draw=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=Math.max(320,rect.width),height=Math.max(340,rect.height);if(canvas.width!==width*dpr||canvas.height!==height*dpr){canvas.width=width*dpr;canvas.height=height*dpr}const context=canvas.getContext("2d");if(!context)return;context.setTransform(dpr,0,0,dpr,0,0);context.fillStyle="#06100f";context.fillRect(0,0,width,height);const frames=framesRef.current;
    if(!frames.length){context.fillStyle="#718078";context.font="11px monospace";context.textAlign="center";context.fillText(status==="no disponible"?"PROFUNDIDAD NO DISPONIBLE":"CONECTANDO CON PROFUNDIDAD DE BINANCE…",width/2,height/2);animation=requestAnimationFrame(draw);return}
    const prices=frames.slice(-80).flatMap(frame=>[...frame.bids,...frame.asks].map(level=>level[0]));let low=Math.min(...prices),high=Math.max(...prices);const rawRange=Math.max(high-low,frames.at(-1)!.mid*.00015),padding=rawRange*.1;low-=padding;high+=padding;const plotTop=18,plotBottom=height-30,plotHeight=plotBottom-plotTop,y=(price:number)=>plotBottom-(price-low)/(high-low)*plotHeight;
    context.strokeStyle="#16342e";context.lineWidth=1;for(let row=0;row<7;row++){const yy=plotTop+row*plotHeight/6;context.beginPath();context.moveTo(0,yy);context.lineTo(width,yy);context.stroke();context.fillStyle="#63736d";context.font="9px monospace";context.textAlign="left";context.fillText(priceLabel(high-(high-low)*row/6),7,yy-4)}
    const columns=140,columnWidth=width/columns;let maxBookQty=.000001,maxTradeQty=.000001;frames.forEach(frame=>{[...frame.bids,...frame.asks].forEach(level=>{maxBookQty=Math.max(maxBookQty,level[1])});frame.trades.forEach(trade=>{maxTradeQty=Math.max(maxTradeQty,trade.qty)})});
    frames.forEach((frame,index)=>{const x=width-(frames.length-index)*columnWidth;[...frame.bids,...frame.asks].forEach(([price,qty])=>{if(price<low||price>high)return;const intensity=Math.min(1,Math.sqrt(qty/maxBookQty));context.fillStyle=intensity>.82?`rgba(255,88,49,${.5+intensity*.4})`:intensity>.55?`rgba(255,218,61,${.35+intensity*.5})`:`rgba(21,151,184,${.17+intensity*.5})`;context.fillRect(x,y(price)-2.5,columnWidth+1.2,5)});frame.trades.forEach(trade=>{if(trade.price<low||trade.price>high)return;const radius=Math.min(14,2.5+Math.sqrt(trade.qty/maxTradeQty)*10);context.beginPath();context.arc(x+columnWidth/2,y(trade.price),radius,0,Math.PI*2);context.fillStyle=trade.buyerMaker?"rgba(255,73,88,.9)":"rgba(42,241,150,.9)";context.fill()})});
    context.strokeStyle="#eaf3ee";context.lineWidth=1.35;context.beginPath();frames.forEach((frame,index)=>{const x=width-(frames.length-index)*columnWidth+columnWidth/2,yy=y(frame.mid);if(index)context.lineTo(x,yy);else context.moveTo(x,yy)});context.stroke();const last=frames.at(-1)!,lastY=Math.max(plotTop+10,Math.min(plotBottom-10,y(last.mid)));context.fillStyle="#ecf4ef";context.fillRect(width-104,lastY-11,104,22);context.fillStyle="#07100f";context.font="bold 11px monospace";context.textAlign="center";context.fillText(priceLabel(last.mid),width-52,lastY+4);
    context.fillStyle="#63736d";context.font="8px monospace";context.textAlign="center";for(let i=0;i<4;i++){const index=Math.max(0,frames.length-1-Math.round(i*(frames.length-1)/3)),frame=frames[index];context.fillText(new Date(frame.time).toLocaleTimeString([],{minute:"2-digit",second:"2-digit"}),width-(frames.length-index)*columnWidth, height-8)}animation=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(animation)},[status]);
  const flowTotal=metrics.buyQty+metrics.sellQty,delta=flowTotal?(metrics.buyQty-metrics.sellQty)/flowTotal*100:0;
  return <section className="panel live-bookmap"><div className="panel-head"><div><p className="eyebrow">MICROESTRUCTURA · BINANCE SPOT</p><h2>Mapa de liquidez y ejecuciones</h2></div><span className={`ws-status ${status.replace(" ","-")}`}>● {status.toUpperCase()}</span></div><div className="bookmap-selector"><label htmlFor="bookmap-symbol">MERCADO</label><select id="bookmap-symbol" value={symbol} onChange={event=>setSymbol(event.target.value)}>{symbols.map(item=><option key={item} value={item}>{base(item)}/USDT</option>)}</select><span>{symbols.length} pares reales disponibles</span></div><div className="flow-metrics"><div><span>MEJOR COMPRA</span><b className="positive">{metrics.bid?priceLabel(metrics.bid):"—"}</b></div><div><span>MEJOR VENTA</span><b className="negative">{metrics.ask?priceLabel(metrics.ask):"—"}</b></div><div><span>SPREAD</span><b>{metrics.spread.toFixed(4)}%</b></div><div><span>IMBALANCE LIBRO</span><b className={metrics.imbalance>=50?"positive":"negative"}>{metrics.imbalance.toFixed(1)}% BID</b></div><div><span>DELTA EJECUTADO</span><b className={delta>=0?"positive":"negative"}>{delta>=0?"+":""}{delta.toFixed(1)}%</b></div></div><div className="bookmap-toolbar"><span>{base(symbol)}/USDT</span><span>{metrics.levels} niveles · {metrics.trades} ejecuciones · {metrics.frames} muestras</span><button onClick={()=>setPaused(value=>!value)}>{paused?"REANUDAR":"PAUSAR"}</button></div><div className="professional-map"><canvas ref={canvasRef} className="bookmap-canvas" role="img" aria-label={`Heatmap de liquidez real de ${base(symbol)} con profundidad y operaciones ejecutadas`}/><aside className="depth-ladder"><div><span>ASK</span><b>PRECIO</b><em>CANT.</em></div>{ladder.asks.slice().reverse().map(([price,qty])=><div className="ask-row" key={`a-${price}`}><span>VENTA</span><b>{priceLabel(price)}</b><em>{qtyLabel(qty)}</em></div>)}<i/><div className="ladder-mid">{metrics.bid&&metrics.ask?priceLabel((metrics.bid+metrics.ask)/2):"—"}</div>{ladder.bids.map(([price,qty])=><div className="bid-row" key={`b-${price}`}><span>COMPRA</span><b>{priceLabel(price)}</b><em>{qtyLabel(qty)}</em></div>)}</aside></div><div className="bookmap-caption"><span><i className="liq"/>Liquidez baja/alta</span><span><i className="buy"/>Compra ejecutada</span><span><i className="sell"/>Venta ejecutada</span><small>Binance WebSocket · 100 ms · desde {started} · representación agregada, no Bookmap oficial</small></div></section>;
}
