"use client";
import { useEffect, useRef, useState } from "react";

type Level=[number,number];
type Trade={price:number;qty:number;buyerMaker:boolean};
type Frame={bids:Level[];asks:Level[];trades:Trade[];mid:number;time:number};
const base=(symbol:string)=>symbol.replace("USDT","");
const priceLabel=(n:number)=>n>=1000?n.toLocaleString("en-US",{maximumFractionDigits:1}):n>=1?n.toFixed(3):n.toPrecision(4);

export default function LiveBookmap({symbols}:{symbols:string[]}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const framesRef=useRef<Frame[]>([]);const bookRef=useRef<{bids:Level[];asks:Level[]}>({bids:[],asks:[]});const tradesRef=useRef<Trade[]>([]);
  const [symbol,setSymbol]=useState("BTCUSDT");const [status,setStatus]=useState<"conectando"|"en vivo"|"no disponible">("conectando");const [paused,setPaused]=useState(false);const pausedRef=useRef(false);const [started,setStarted]=useState("");
  useEffect(()=>{pausedRef.current=paused},[paused]);
  useEffect(()=>{framesRef.current=[];bookRef.current={bids:[],asks:[]};tradesRef.current=[];const boot=setTimeout(()=>{setStatus("conectando");setStarted(new Date().toLocaleTimeString())},0);let closed=false,retry:ReturnType<typeof setTimeout>;const key=symbol.toLowerCase();
    const connect=(host:string)=>{const ws=new WebSocket(`${host}/stream?streams=${key}@depth20@100ms/${key}@aggTrade`);ws.onopen=()=>setStatus("en vivo");ws.onmessage=e=>{try{const msg=JSON.parse(e.data);const d=msg.data;if(d?.e==="depthUpdate"){bookRef.current={bids:(d.b??[]).map((x:string[])=>[Number(x[0]),Number(x[1])]),asks:(d.a??[]).map((x:string[])=>[Number(x[0]),Number(x[1])])}}else if(d?.e==="aggTrade"){tradesRef.current.push({price:Number(d.p),qty:Number(d.q),buyerMaker:Boolean(d.m)});if(tradesRef.current.length>80)tradesRef.current.shift()}}catch{return}};ws.onerror=()=>ws.close();ws.onclose=()=>{if(closed)return;setStatus("conectando");retry=setTimeout(()=>connect(host.includes("binance.com")?"wss://data-stream.binance.vision":"wss://stream.binance.com:9443"),1500)};return ws};
    const ws=connect("wss://stream.binance.com:9443");const capture=setInterval(()=>{if(pausedRef.current)return;const b=bookRef.current;if(!b.bids.length||!b.asks.length)return;const mid=(b.bids[0][0]+b.asks[0][0])/2;framesRef.current.push({bids:b.bids.map(x=>[...x] as Level),asks:b.asks.map(x=>[...x] as Level),trades:tradesRef.current.splice(0),mid,time:Date.now()});if(framesRef.current.length>100)framesRef.current.shift()},500);
    return()=>{closed=true;clearTimeout(boot);clearTimeout(retry);clearInterval(capture);ws.close()}
  },[symbol]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;let raf=0;const draw=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(320,rect.width),h=Math.max(300,rect.height);if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}const c=canvas.getContext("2d");if(!c)return;c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle="#07100f";c.fillRect(0,0,w,h);const frames=framesRef.current;if(!frames.length){c.fillStyle="#718078";c.font="12px monospace";c.textAlign="center";c.fillText(status==="no disponible"?"DATOS NO DISPONIBLES":"ACUMULANDO PROFUNDIDAD REAL…",w/2,h/2);raf=requestAnimationFrame(draw);return}const mids=frames.map(f=>f.mid),center=mids[mids.length-1],span=Math.max(center*.006,...frames.flatMap(f=>[...f.bids,...f.asks].map(x=>Math.abs(x[0]-center))).filter(x=>x<center*.018));const min=center-span,max=center+span;const y=(p:number)=>h-28-(p-min)/(max-min)*(h-50);const col=w/100;let maxQty=0;frames.forEach(f=>[...f.bids,...f.asks].forEach(x=>{if(x[0]>=min&&x[0]<=max)maxQty=Math.max(maxQty,x[1])}));maxQty=Math.max(maxQty,.0001);
      c.strokeStyle="#173229";c.lineWidth=1;for(let i=0;i<6;i++){const yy=20+i*(h-48)/5;c.beginPath();c.moveTo(0,yy);c.lineTo(w,yy);c.stroke();c.fillStyle="#708079";c.font="9px monospace";c.textAlign="left";c.fillText(priceLabel(max-(max-min)*i/5),5,yy-3)}
      frames.forEach((f,fi)=>{const x=w-(frames.length-fi)*col;[...f.bids,...f.asks].forEach(([p,q])=>{if(p<min||p>max)return;const intensity=Math.min(1,Math.sqrt(q/maxQty));c.fillStyle=intensity>.72?`rgba(255,220,70,${.25+intensity*.7})`:`rgba(24,139,166,${.12+intensity*.55})`;c.fillRect(x,y(p)-2,col+1,4)});f.trades.forEach(t=>{if(t.price<min||t.price>max)return;const r=Math.min(13,2+Math.sqrt(t.qty/maxQty)*9);c.beginPath();c.arc(x+col/2,y(t.price),r,0,Math.PI*2);c.fillStyle=t.buyerMaker?"rgba(255,72,84,.82)":"rgba(50,245,150,.82)";c.fill()})});
      c.strokeStyle="#e5eee9";c.lineWidth=1.4;c.beginPath();frames.forEach((f,i)=>{const x=w-(frames.length-i)*col+col/2,yy=y(f.mid);if(i)c.lineTo(x,yy);else c.moveTo(x,yy)});c.stroke();const lastY=y(center);c.fillStyle="#e5eee9";c.fillRect(w-92,lastY-10,92,20);c.fillStyle="#07100f";c.font="bold 10px monospace";c.textAlign="center";c.fillText(priceLabel(center),w-46,lastY+4);raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[status]);
  return <section className="panel live-bookmap"><div className="panel-head"><div><p className="eyebrow">ORDER FLOW · WEBSOCKET REAL</p><h2>Heatmap de liquidez en vivo</h2></div><span className={`ws-status ${status.replace(" ","-")}`}>● {status.toUpperCase()}</span></div><div className="asset-tabs">{symbols.filter(s=>["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT","DOGEUSDT","AVAXUSDT","LINKUSDT","SUIUSDT","DOTUSDT","LTCUSDT"].includes(s)).map(s=><button className={s===symbol?"active":""} key={s} onClick={()=>setSymbol(s)}>{base(s)}</button>)}</div><div className="bookmap-toolbar"><span>{base(symbol)}/USDT</span><span>Historial real desde {started}</span><button onClick={()=>setPaused(v=>!v)}>{paused?"REANUDAR":"PAUSAR"}</button></div><canvas ref={canvasRef} className="bookmap-canvas" role="img" aria-label={`Heatmap de liquidez real de ${base(symbol)} con profundidad y operaciones ejecutadas`}/><div className="bookmap-caption"><span><i className="liq"/>Liquidez visible</span><span><i className="buy"/>Compra ejecutada</span><span><i className="sell"/>Venta ejecutada</span><small>Fuente: Binance WebSocket · profundidad 100 ms · operaciones reales agregadas</small></div></section>
}
