"use client";
import { useEffect, useRef, useState } from "react";

type Level=[number,number];
type Trade={price:number;qty:number;buyerMaker:boolean};
type TapeTrade=Trade&{time:number;large:boolean};
type Liquidation={time:number;side:"LONG"|"SHORT";price:number;qty:number;notional:number};
type Frame={bids:Level[];asks:Level[];trades:Trade[];mid:number;time:number};
type Metrics={levels:number;trades:number;frames:number;imbalance:number;spread:number;buyQty:number;sellQty:number;bid:number;ask:number};
type AltseasonContext={score:number|null;raw:number|null;adjustment:number;state:string};
const EMPTY_METRICS:Metrics={levels:0,trades:0,frames:0,imbalance:50,spread:0,buyQty:0,sellQty:0,bid:0,ask:0};
const base=(symbol:string)=>symbol.replace("USDT","");
const priceLabel=(n:number)=>n>=1000?n.toLocaleString("en-US",{maximumFractionDigits:2}):n>=1?n.toFixed(3):n.toPrecision(5);
const qtyLabel=(n:number)=>new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(n);

export default function LiveBookmap({symbols,altseason}:{symbols:string[];altseason:AltseasonContext}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const framesRef=useRef<Frame[]>([]);const bookRef=useRef<{bids:Level[];asks:Level[]}>({bids:[],asks:[]});const pendingTradesRef=useRef<Trade[]>([]);const tapeRef=useRef<(Trade&{time:number})[]>([]);const cvdRef=useRef<{time:number;value:number}[]>([]);const liquidationsRef=useRef<Liquidation[]>([]);const totalsRef=useRef({trades:0,buyQty:0,sellQty:0});
  const [symbol,setSymbol]=useState("BTCUSDT");const [venue,setVenue]=useState<"spot"|"futures">("spot");const [futuresSymbols,setFuturesSymbols]=useState<string[]>([]);const [status,setStatus]=useState<"conectando"|"en vivo"|"no disponible">("conectando");const [paused,setPaused]=useState(false);const pausedRef=useRef(false);const [started,setStarted]=useState("");const [metrics,setMetrics]=useState<Metrics>(EMPTY_METRICS);const [ladder,setLadder]=useState<{bids:Level[];asks:Level[]}>({bids:[],asks:[]});const [tape,setTape]=useState<TapeTrade[]>([]);const [liquidations,setLiquidations]=useState<Liquidation[]>([]);const [sampleMs,setSampleMs]=useState(500);const [depth,setDepth]=useState(20);const [scale,setScale]=useState<"log"|"linear">("log");
  useEffect(()=>{pausedRef.current=paused},[paused]);
  useEffect(()=>{let alive=true;fetch("https://fapi.binance.com/fapi/v1/exchangeInfo").then(response=>response.ok?response.json():Promise.reject()).then((data:{symbols?:{symbol:string;quoteAsset:string;status:string}[]})=>{if(alive)setFuturesSymbols((data.symbols??[]).filter(item=>item.quoteAsset==="USDT"&&item.status==="TRADING").map(item=>item.symbol))}).catch(()=>undefined);return()=>{alive=false}},[]);
  useEffect(()=>{
    framesRef.current=[];bookRef.current={bids:[],asks:[]};pendingTradesRef.current=[];tapeRef.current=[];cvdRef.current=[];liquidationsRef.current=[];totalsRef.current={trades:0,buyQty:0,sellQty:0};
    const boot=setTimeout(()=>{setStatus("conectando");setStarted(new Date().toLocaleTimeString());setMetrics(EMPTY_METRICS);setLadder({bids:[],asks:[]});setTape([]);setLiquidations([])},0);let closed=false,retry:ReturnType<typeof setTimeout>;let watchdog:ReturnType<typeof setTimeout>;const key=symbol.toLowerCase();
    const connect=(host:string)=>{
      const streams=`${key}@depth${depth}@100ms/${key}@${venue==="futures"?"trade":"aggTrade"}${venue==="futures"?`/${key}@forceOrder`:""}`;const ws=new WebSocket(`${host}/stream?streams=${streams}`);let receivedDepth=false;
      watchdog=setTimeout(()=>{if(!receivedDepth)ws.close()},9000);
      ws.onmessage=event=>{try{const message=JSON.parse(event.data);const data=message.data??message;const rawBids=data?.b??data?.bids,rawAsks=data?.a??data?.asks;
        if(Array.isArray(rawBids)&&Array.isArray(rawAsks)){const bids=rawBids.map((x:string[])=>[Number(x[0]),Number(x[1])] as Level).filter(x=>x[0]>0&&x[1]>=0);const asks=rawAsks.map((x:string[])=>[Number(x[0]),Number(x[1])] as Level).filter(x=>x[0]>0&&x[1]>=0);if(bids.length&&asks.length){bookRef.current={bids,asks};receivedDepth=true;setStatus("en vivo")}}
        else if(data?.e==="aggTrade"||data?.e==="trade"){const trade={price:Number(data.p),qty:Number(data.q),buyerMaker:Boolean(data.m)};if(trade.price>0&&trade.qty>0){pendingTradesRef.current.push(trade);tapeRef.current.push({...trade,time:Number(data.T)||Date.now()});if(pendingTradesRef.current.length>180)pendingTradesRef.current.shift();if(tapeRef.current.length>240)tapeRef.current.shift();totalsRef.current.trades+=1;if(trade.buyerMaker)totalsRef.current.sellQty+=trade.qty;else totalsRef.current.buyQty+=trade.qty}}
        else if(data?.e==="forceOrder"&&data.o){const price=Number(data.o.ap||data.o.p),qty=Number(data.o.z||data.o.q);if(price>0&&qty>0){liquidationsRef.current.push({time:Number(data.o.T||data.E)||Date.now(),side:data.o.S==="SELL"?"LONG":"SHORT",price,qty,notional:price*qty});if(liquidationsRef.current.length>40)liquidationsRef.current.shift()}}
      }catch{return}};
      ws.onerror=()=>ws.close();ws.onclose=()=>{clearTimeout(watchdog);if(closed)return;setStatus("conectando");const next=venue==="futures"?"wss://fstream.binance.com":host.includes("stream.binance.com")?"wss://data-stream.binance.vision":"wss://stream.binance.com:9443";retry=setTimeout(()=>connect(next),1200)};return ws;
    };
    const ws=connect(venue==="futures"?"wss://fstream.binance.com":"wss://stream.binance.com:9443");
    const capture=setInterval(()=>{if(pausedRef.current)return;const book=bookRef.current;if(!book.bids.length||!book.asks.length)return;const trades=pendingTradesRef.current.splice(0);const bid=book.bids[0][0],ask=book.asks[0][0],mid=(bid+ask)/2;framesRef.current.push({bids:book.bids.slice(0,depth).map(x=>[...x] as Level),asks:book.asks.slice(0,depth).map(x=>[...x] as Level),trades,mid,time:Date.now()});if(framesRef.current.length>140)framesRef.current.shift();cvdRef.current.push({time:Date.now(),value:totalsRef.current.buyQty-totalsRef.current.sellQty});if(cvdRef.current.length>140)cvdRef.current.shift();const bidQty=book.bids.reduce((sum,x)=>sum+x[1],0),askQty=book.asks.reduce((sum,x)=>sum+x[1],0),total=bidQty+askQty;const recent=tapeRef.current.slice(-100),sorted=recent.map(item=>item.qty).sort((a,b)=>a-b),largeAt=sorted[Math.max(0,Math.floor(sorted.length*.9))]??Infinity;setTape(recent.slice(-18).reverse().map(item=>({...item,large:item.qty>=largeAt})));setLiquidations(liquidationsRef.current.slice(-8).reverse());setLadder({bids:book.bids.slice(0,6),asks:book.asks.slice(0,6)});setMetrics({levels:book.bids.length+book.asks.length,trades:totalsRef.current.trades,frames:framesRef.current.length,imbalance:total?bidQty/total*100:50,spread:mid?(ask-bid)/mid*100:0,buyQty:totalsRef.current.buyQty,sellQty:totalsRef.current.sellQty,bid,ask})},sampleMs);
    return()=>{closed=true;clearTimeout(boot);clearTimeout(retry);clearTimeout(watchdog);clearInterval(capture);ws.close()};
  },[symbol,venue,sampleMs,depth]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;let animation=0;const draw=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=Math.max(320,rect.width),height=Math.max(340,rect.height);if(canvas.width!==width*dpr||canvas.height!==height*dpr){canvas.width=width*dpr;canvas.height=height*dpr}const context=canvas.getContext("2d");if(!context)return;context.setTransform(dpr,0,0,dpr,0,0);context.fillStyle="#06100f";context.fillRect(0,0,width,height);const frames=framesRef.current;
    if(!frames.length){context.fillStyle="#718078";context.font="11px monospace";context.textAlign="center";context.fillText(status==="no disponible"?"PROFUNDIDAD NO DISPONIBLE":"CONECTANDO CON PROFUNDIDAD DE BINANCE…",width/2,height/2);animation=requestAnimationFrame(draw);return}
    const prices=frames.slice(-80).flatMap(frame=>[...frame.bids,...frame.asks].map(level=>level[0]));let low=Math.min(...prices),high=Math.max(...prices);const rawRange=Math.max(high-low,frames.at(-1)!.mid*.00015),padding=rawRange*.1;low-=padding;high+=padding;const plotTop=18,plotBottom=height-104,plotHeight=plotBottom-plotTop,y=(price:number)=>plotBottom-(price-low)/(high-low)*plotHeight;
    context.strokeStyle="#16342e";context.lineWidth=1;for(let row=0;row<7;row++){const yy=plotTop+row*plotHeight/6;context.beginPath();context.moveTo(0,yy);context.lineTo(width,yy);context.stroke();context.fillStyle="#63736d";context.font="9px monospace";context.textAlign="left";context.fillText(priceLabel(high-(high-low)*row/6),7,yy-4)}
    const columns=140,columnWidth=width/columns;let maxBookQty=.000001,maxTradeQty=.000001;frames.forEach(frame=>{[...frame.bids,...frame.asks].forEach(level=>{maxBookQty=Math.max(maxBookQty,level[1])});frame.trades.forEach(trade=>{maxTradeQty=Math.max(maxTradeQty,trade.qty)})});const tradeSizes=frames.flatMap(frame=>frame.trades.map(trade=>trade.qty)).sort((a,b)=>a-b),largeTradeAt=tradeSizes[Math.max(0,Math.floor(tradeSizes.length*.9))]??Infinity;
    frames.forEach((frame,index)=>{const x=width-(frames.length-index)*columnWidth;[...frame.bids,...frame.asks].forEach(([price,qty])=>{if(price<low||price>high)return;const intensity=Math.min(1,scale==="log"?Math.log1p(qty)/Math.log1p(maxBookQty):qty/maxBookQty);context.fillStyle=intensity>.82?`rgba(255,88,49,${.5+intensity*.4})`:intensity>.55?`rgba(255,218,61,${.35+intensity*.5})`:`rgba(21,151,184,${.17+intensity*.5})`;context.fillRect(x,y(price)-2.5,columnWidth+1.2,5)});frame.trades.forEach(trade=>{if(trade.price<low||trade.price>high)return;const radius=Math.min(14,2.5+Math.sqrt(trade.qty/maxTradeQty)*10);context.beginPath();context.arc(x+columnWidth/2,y(trade.price),radius,0,Math.PI*2);context.fillStyle=trade.buyerMaker?"rgba(255,73,88,.9)":"rgba(42,241,150,.9)";context.fill();if(trade.qty>=largeTradeAt){context.strokeStyle="#fff6b0";context.lineWidth=1.4;context.stroke()}})});
    context.strokeStyle="#eaf3ee";context.lineWidth=1.35;context.beginPath();frames.forEach((frame,index)=>{const x=width-(frames.length-index)*columnWidth+columnWidth/2,yy=y(frame.mid);if(index)context.lineTo(x,yy);else context.moveTo(x,yy)});context.stroke();const last=frames.at(-1)!,lastY=Math.max(plotTop+10,Math.min(plotBottom-10,y(last.mid)));context.fillStyle="#ecf4ef";context.fillRect(width-104,lastY-11,104,22);context.fillStyle="#07100f";context.font="bold 11px monospace";context.textAlign="center";context.fillText(priceLabel(last.mid),width-52,lastY+4);
    context.fillStyle="#63736d";context.font="8px monospace";context.textAlign="center";for(let i=0;i<4;i++){const index=Math.max(0,frames.length-1-Math.round(i*(frames.length-1)/3)),frame=frames[index];context.fillText(new Date(frame.time).toLocaleTimeString([],{minute:"2-digit",second:"2-digit"}),width-(frames.length-index)*columnWidth,plotBottom+14)}const cvd=cvdRef.current;if(cvd.length>1){const values=cvd.map(item=>item.value),cvdMin=Math.min(...values),cvdMax=Math.max(...values),cvdRange=Math.max(cvdMax-cvdMin,.000001),cvdTop=plotBottom+31,cvdBottom=height-12,cy=(value:number)=>cvdBottom-(value-cvdMin)/cvdRange*(cvdBottom-cvdTop);context.strokeStyle="#213a31";context.beginPath();context.moveTo(0,cvdTop-8);context.lineTo(width,cvdTop-8);context.stroke();context.fillStyle="#718078";context.font="8px monospace";context.textAlign="left";context.fillText("CVD ACUMULADO",7,cvdTop);context.strokeStyle=values.at(-1)!>=values[0]?"#39f29a":"#ff5964";context.lineWidth=1.4;context.beginPath();cvd.forEach((item,index)=>{const x=width-(cvd.length-index)*columnWidth,yy=cy(item.value);if(index)context.lineTo(x,yy);else context.moveTo(x,yy)});context.stroke()}animation=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(animation)},[status,scale]);
  const flowTotal=metrics.buyQty+metrics.sellQty,delta=flowTotal?(metrics.buyQty-metrics.sellQty)/flowTotal*100:0,cvd=metrics.buyQty-metrics.sellQty;
  const availableSymbols=venue==="futures"&&futuresSymbols.length?symbols.filter(item=>futuresSymbols.includes(item)):symbols;
  const changeVenue=(next:"spot"|"futures")=>{setVenue(next);if(next==="futures"&&futuresSymbols.length&&!futuresSymbols.includes(symbol))setSymbol(futuresSymbols.includes("BTCUSDT")?"BTCUSDT":futuresSymbols[0])};
  const footprint=(()=>{if(!tape.length||!metrics.bid)return[];const step=Math.max(metrics.bid*.00015,Number.EPSILON),rows=new Map<number,{buy:number;sell:number}>();tape.forEach(trade=>{const price=Math.round(trade.price/step)*step,current=rows.get(price)??{buy:0,sell:0};if(trade.buyerMaker)current.sell+=trade.qty;else current.buy+=trade.qty;rows.set(price,current)});return [...rows.entries()].sort((a,b)=>b[0]-a[0]).slice(0,9)})();
  const largeTrades=tape.filter(trade=>trade.large),largeBuy=largeTrades.filter(trade=>!trade.buyerMaker).reduce((sum,trade)=>sum+trade.qty,0),largeSell=largeTrades.filter(trade=>trade.buyerMaker).reduce((sum,trade)=>sum+trade.qty,0),largeTotal=largeBuy+largeSell,largeDelta=largeTotal?(largeBuy-largeSell)/largeTotal*100:0;
  const buyerPower=Math.round(Math.max(0,Math.min(100,50+delta*.25+(metrics.imbalance-50)*.45+largeDelta*.15))),sellerPower=100-buyerPower,winner=buyerPower>=60?"COMPRADORES":buyerPower<=40?"VENDEDORES":"EQUILIBRIO",winnerConfidence=Math.round(Math.abs(buyerPower-50)*2);
  const confluence=altseason.score===null?"CONTEXTO INCOMPLETO":winner==="COMPRADORES"&&altseason.score>=61?"CONFLUENCIA ALCISTA":winner==="VENDEDORES"?"PRESIÓN VENDEDORA":altseason.score>=61?"ALTSEASON SIN TRIGGER":"SIN CONFLUENCIA";
  return <section className="panel live-bookmap">
    <div className="panel-head"><div><p className="eyebrow">ORDER FLOW PRO · BINANCE {venue==="futures"?"FUTUROS":"SPOT"}</p><h2>Mapa de liquidez, footprint y CVD</h2></div><span className={`ws-status ${status.replace(" ","-")}`}>● {status.toUpperCase()}</span></div>
    <div className="bookmap-selector"><label htmlFor="bookmap-symbol">MERCADO</label><select id="bookmap-symbol" value={symbol} onChange={event=>setSymbol(event.target.value)}>{availableSymbols.map(item=><option key={item} value={item}>{base(item)}/USDT</option>)}</select><span>{availableSymbols.length} pares reales disponibles</span></div>
    <div className="heatmap-controls"><label>FUENTE<select value={venue} onChange={event=>changeVenue(event.target.value as "spot"|"futures")}><option value="spot">Binance Spot</option><option value="futures">Binance Futuros</option></select></label><label>PROFUNDIDAD<select value={depth} onChange={event=>setDepth(Number(event.target.value))}><option value={5}>5 niveles</option><option value={10}>10 niveles</option><option value={20}>20 niveles</option></select></label><label>MUESTREO<select value={sampleMs} onChange={event=>setSampleMs(Number(event.target.value))}><option value={250}>250 ms</option><option value={500}>500 ms</option><option value={1000}>1 segundo</option></select></label><label>ESCALA<select value={scale} onChange={event=>setScale(event.target.value as "log"|"linear")}><option value="log">Logarítmica</option><option value="linear">Lineal</option></select></label></div>
    <div className="flow-metrics"><div><span>MEJOR COMPRA</span><b className="positive">{metrics.bid?priceLabel(metrics.bid):"—"}</b></div><div><span>MEJOR VENTA</span><b className="negative">{metrics.ask?priceLabel(metrics.ask):"—"}</b></div><div><span>SPREAD</span><b>{metrics.spread.toFixed(4)}%</b></div><div><span>IMBALANCE LIBRO</span><b className={metrics.imbalance>=50?"positive":"negative"}>{metrics.imbalance.toFixed(1)}% BID</b></div><div><span>DELTA EJECUTADO</span><b className={delta>=0?"positive":"negative"}>{delta>=0?"+":""}{delta.toFixed(1)}%</b></div><div><span>CVD ACUMULADO</span><b className={cvd>=0?"positive":"negative"}>{cvd>=0?"+":""}{qtyLabel(cvd)}</b></div></div>
    <section className="decision-board"><article className={`battle-card ${winner.toLowerCase()}`}><div className="decision-title"><span>BATALLA DE FLUJO</span><b>GANANDO AHORA: {winner}</b></div><div className="battle-numbers"><strong className="negative">{sellerPower}%<small>VENDEDORES</small></strong><div className="battle-track"><i style={{left:`${sellerPower}%`}}/><span style={{width:`${sellerPower}%`}}/><b style={{width:`${buyerPower}%`}}/></div><strong className="positive">{buyerPower}%<small>COMPRADORES</small></strong></div><div className="battle-reasons"><span>Delta {delta>=0?"+":""}{delta.toFixed(1)}%</span><span>Libro {metrics.imbalance.toFixed(1)}% bid</span><span>Grandes {largeDelta>=0?"+":""}{largeDelta.toFixed(1)}%</span><em>Confianza direccional {winnerConfidence}%</em></div></article><article className="altseason-live"><div className="alt-live-ring" style={{"--alt-live":`${(altseason.score??0)*3.6}deg`} as React.CSSProperties}><b>{altseason.score??"—"}</b><small>/100</small></div><div><span>ENTORNO ALTSEASON</span><h3>{altseason.state}</h3><p><i>TÉCNICO {altseason.raw??"—"}</i><i>MACRO {altseason.adjustment}</i><i>FINAL {altseason.score??"—"}</i></p></div></article><article className={`confluence-card ${confluence.toLowerCase().replaceAll(" ","-")}`}><span>LECTURA COMBINADA</span><h3>{confluence}</h3><p>{confluence==="CONFLUENCIA ALCISTA"?"El flujo comprador coincide con un entorno de rotación favorable.":confluence==="PRESIÓN VENDEDORA"?"La oferta domina el flujo actual. No perseguir entradas largas.":"Falta alineación suficiente entre flujo y contexto de mercado."}</p><small>Lectura probabilística · no constituye señal por sí sola</small></article></section>
    <div className="bookmap-toolbar"><span>{base(symbol)}/USDT</span><span>{metrics.levels} niveles · {metrics.trades} ejecuciones · {metrics.frames} muestras</span><button onClick={()=>setPaused(value=>!value)}>{paused?"REANUDAR":"PAUSAR"}</button></div>
    <div className="professional-map"><canvas ref={canvasRef} className="bookmap-canvas" role="img" aria-label={`Heatmap de liquidez real de ${base(symbol)} con profundidad y operaciones ejecutadas`}/><aside className="market-sidebar"><div className="depth-ladder"><header>PROFUNDIDAD ACTUAL</header><div><span>ASK</span><b>PRECIO</b><em>CANT.</em></div>{ladder.asks.slice().reverse().map(([price,qty])=><div className="ask-row" key={`a-${price}`}><span>VENTA</span><b>{priceLabel(price)}</b><em>{qtyLabel(qty)}</em></div>)}<i/><div className="ladder-mid">{metrics.bid&&metrics.ask?priceLabel((metrics.bid+metrics.ask)/2):"—"}</div>{ladder.bids.map(([price,qty])=><div className="bid-row" key={`b-${price}`}><span>COMPRA</span><b>{priceLabel(price)}</b><em>{qtyLabel(qty)}</em></div>)}</div><div className="time-sales"><header>TIME &amp; SALES <span>● GRANDES</span></header>{tape.map((trade,index)=><div className={`${trade.buyerMaker?"sale":"buy"} ${trade.large?"large":""}`} key={`${trade.time}-${index}`}><time>{new Date(trade.time).toLocaleTimeString([],{minute:"2-digit",second:"2-digit"})}</time><b>{priceLabel(trade.price)}</b><em>{qtyLabel(trade.qty)}</em></div>)}{!tape.length&&<p>ESPERANDO EJECUCIONES…</p>}</div><div className="footprint"><header>FOOTPRINT AGREGADO</header>{footprint.map(([price,row])=><div key={price}><b className="negative">{qtyLabel(row.sell)}</b><span>{priceLabel(price)}</span><b className="positive">{qtyLabel(row.buy)}</b></div>)}{!footprint.length&&<p>DATOS NO DISPONIBLES</p>}</div><div className="liquidation-tape"><header>LIQUIDACIONES REALES</header>{venue==="spot"?<p>DISPONIBLE EN BINANCE FUTUROS</p>:liquidations.length?liquidations.map(item=><div className={item.side==="LONG"?"long":"short"} key={`${item.time}-${item.price}`}><time>{new Date(item.time).toLocaleTimeString([],{minute:"2-digit",second:"2-digit"})}</time><b>{item.side}</b><span>${qtyLabel(item.notional)}</span></div>):<p>SIN LIQUIDACIONES RECIBIDAS</p>}</div></aside></div>
    <div className="bookmap-caption"><span><i className="liq"/>Liquidez baja/alta</span><span><i className="buy"/>Compra ejecutada</span><span><i className="sell"/>Venta ejecutada</span><small>Binance {venue==="futures"?"Futures":"Spot"} WebSocket · desde {started} · datos reales · motor Canvas propio inspirado en <a href="https://github.com/Elenchev/order-book-heatmap" target="_blank" rel="noreferrer">Order Book Heatmap (BSD-2)</a></small></div>
  </section>;
}
