"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { RadarPayload, ScoredAsset } from "@/lib/radar";
import { altseasonScore, globalRisk, rotation, scoreAssets } from "@/lib/radar";
import LiveBookmap from "./live-bookmap";
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};

const fmtPrice = (v: number) => v >= 1000 ? `$${v.toLocaleString("en-US", { maximumFractionDigits: 0 })}` : v >= 1 ? `$${v.toFixed(2)}` : `$${v.toPrecision(3)}`;
const pct = (v: number | null) => v === null ? "—" : `${v >= 0 ? "+" : ""}${v.toFixed(2)}%`;
const compact = (v: number) => new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(v);
const assetName = (s: string) => s.replace("USDT", "");
const DIRECT_SYMBOLS=new Set(["BTC","ETH","BNB","SOL","XRP","ADA","DOGE","AVAX","LINK","SUI","DOT","NEAR","ARB","OP","APT","INJ","SEI","LTC","UNI","ATOM"]);
async function loadDirectMarket():Promise<RadarPayload>{
  const [tickersRes,globalRes]=await Promise.all([fetch("https://api.coinlore.net/api/tickers/?start=0&limit=100",{cache:"no-store"}),fetch("https://api.coinlore.net/api/global/",{cache:"no-store"})]);
  if(!tickersRes.ok)throw new Error();const tickers=await tickersRes.json() as {data:{symbol:string;price_usd:string;percent_change_1h:string;percent_change_24h:string;volume24:number;volume24_native?:number}[]};
  const global=globalRes.ok?await globalRes.json() as {btc_d?:string;mcap_change?:string}[]:[];
  return {timestamp:new Date().toISOString(),sources:["CoinLore Market · conexión directa"],market:tickers.data.filter(x=>DIRECT_SYMBOLS.has(x.symbol)).map(x=>({symbol:`${x.symbol}USDT`,price:Number(x.price_usd),change1h:Number(x.percent_change_1h),change4h:null,change24h:Number(x.percent_change_24h),volume:Number(x.volume24_native??0),quoteVolume:Number(x.volume24),high:null,low:null})),dominance:{btc:global[0]?.btc_d?Number(global[0].btc_d):null,change24h:global[0]?.mcap_change?Number(global[0].mcap_change):null},news:[],errors:["Modo directo activo; algunos datos avanzados pueden no estar disponibles"]};
}

function ScoreRing({ score, label }: { score: number | null; label: string }) {
  const n = score ?? 0;
  return <div className="score-ring" style={{ "--score": `${n * 3.6}deg` } as React.CSSProperties}><div><b>{score ?? "—"}</b><span>/100</span><small>{label}</small></div></div>;
}

function SparkBars({ values }: { values: number[] }) { const max = Math.max(...values.map(Math.abs), 1); return <div className="spark">{values.map((v, i) => <i key={i} className={v >= 0 ? "up" : "down"} style={{ height: `${22 + Math.abs(v) / max * 72}%` }} />)}</div>; }

type BookData={symbol:string;source:string|null;timestamp:string;bids:string[][];asks:string[][];error?:string};
function LiquidityMap({symbols}:{symbols:string[]}){
  const [symbol,setSymbol]=useState("BTCUSDT"); const [book,setBook]=useState<BookData|null>(null); const [busy,setBusy]=useState(true);
  useEffect(()=>{let alive=true; const load=async()=>{setBusy(true);try{const server=fetch(`/api/orderbook?symbol=${symbol}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const j=await r.json();if(!j.bids?.length)throw new Error();return j});const direct=fetch(`https://data-api.binance.vision/api/v3/depth?symbol=${symbol}&limit=100`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const j=await r.json();return {symbol,source:"Binance Data API · conexión directa",timestamp:new Date().toISOString(),bids:j.bids.slice(0,40),asks:j.asks.slice(0,40)}});const j=await Promise.any([direct,server]);if(alive)setBook(j)}catch{if(alive)setBook({symbol,source:null,timestamp:new Date().toISOString(),bids:[],asks:[],error:"Libro de órdenes no disponible para este activo"})}finally{if(alive)setBusy(false)}};load();const id=setInterval(load,10000);return()=>{alive=false;clearInterval(id)}},[symbol]);
  const bids=book?.bids.slice(0,18)??[],asks=book?.asks.slice(0,18)??[];const all=[...bids,...asks];const max=Math.max(1,...all.map(x=>Number(x[1])));const rows=[...asks].reverse().slice(-12).map(x=>({side:"ask",price:Number(x[0]),qty:Number(x[1])})).concat(bids.slice(0,12).map(x=>({side:"bid",price:Number(x[0]),qty:Number(x[1])})));
  return <section className="panel liquidity-map"><div className="panel-head"><div><p className="eyebrow">LIQUIDEZ EN TIEMPO REAL</p><h2>Mapa de órdenes</h2></div><span className="status-dot">● {busy?"ACTUALIZANDO":book?.source??"NO DISPONIBLE"}</span></div><div className="asset-tabs">{symbols.slice(0,14).map(s=><button className={s===symbol?"active":""} key={s} onClick={()=>setSymbol(s)}>{assetName(s)}</button>)}</div>{rows.length?<div className="bookmap"><div className="heat-grid">{rows.map((row,i)=><div className={`heat-row ${row.side}`} key={`${row.side}-${row.price}-${i}`}><i style={{width:`${Math.max(2,row.qty/max*100)}%`}}/><span>{fmtPrice(row.price)}</span><em>{compact(row.qty)} {assetName(symbol)}</em></div>)}<div className="midline"><b>{assetName(symbol)}/USDT</b><span>SPREAD / PROFUNDIDAD OBSERVADA</span></div></div><div className="book-legend"><span><i className="bid"/>COMPRAS</span><span><i className="ask"/>VENTAS</span><small>Intensidad = cantidad visible por nivel · Snapshot, no historial</small></div></div>:<div className="empty book-empty">{busy?"CARGANDO LIBRO DE ÓRDENES…":book?.error??"DATOS NO DISPONIBLES"}</div>}<div className="map-foot"><span>Fuente: {book?.source??"no disponible"}</span><span>{book?.timestamp?new Date(book.timestamp).toLocaleTimeString():"—"}</span><span>Actualización cada 10 s</span></div></section>
}

function MarketStrip({ data }: { data: RadarPayload }) {
  const symbols = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT"];
  return <div className="market-strip">{symbols.map(s => { const a = data.market.find(x => x.symbol === s); return <div className="market-tile" key={s}><span>{assetName(s)} <em>SPOT</em></span>{a ? <><strong>{fmtPrice(a.price)}</strong><small className={a.change24h >= 0 ? "positive" : "negative"}>{pct(a.change24h)} 24H</small></> : <strong className="muted">DATOS NO DISPONIBLES</strong>}</div>; })}<div className="market-tile"><span>BTC.D <em>GLOBAL</em></span><strong>{data.dominance.btc === null ? "—" : `${data.dominance.btc.toFixed(2)}%`}</strong><small className="muted">COINGECKO</small></div></div>;
}

function SignalDrawer({ asset, close, alt }: { asset: ScoredAsset; close: () => void; alt: number | null }) {
  const observedRange = asset.high !== null && asset.low !== null ? asset.high - asset.low : null; const atr = observedRange ? Math.max(observedRange * .15, asset.price * .012) : asset.price * .012; const entryLow = asset.price - atr * .15; const stop = asset.price - atr; const risk = asset.price - stop;
  return <div className="overlay"><aside className="drawer"><button className="close" onClick={close}>×</button><p className="eyebrow">INTELIGENCIA DE SEÑAL / {new Date().toLocaleTimeString()}</p><h2>{assetName(asset.symbol)}<span>/USDT</span></h2><div className={`signal-banner ${asset.signal.toLowerCase().replace(" ", "-")}`}>{asset.extended ? "⚠ MOVIMIENTO YA EXTENDIDO · NO PERSEGUIR" : asset.signal}</div><div className="trade-grid"><div><span>ZONA DE ENTRADA</span><b>{fmtPrice(entryLow)} – {fmtPrice(asset.price)}</b></div><div><span>INVALIDACIÓN</span><b>{fmtPrice(stop)}</b></div><div><span>OBJETIVO 1</span><b>{fmtPrice(asset.price + risk * 1.4)}</b></div><div><span>OBJETIVO 2</span><b>{fmtPrice(asset.price + risk * 2.1)}</b></div><div><span>OBJETIVO 3</span><b>{fmtPrice(asset.price + risk * 3)}</b></div><div><span>R:R ESPERADO</span><b>1 : 3.0</b></div></div><h3>TRAZA DE DECISIÓN</h3><div className="explain-list">{asset.reasons.map(r => <div key={r.label}><span>+{r.points}</span>{r.label}</div>)}{asset.penalties.map(r => <div className="penalty" key={r.label}><span>{r.points}</span>{r.label}</div>)}</div><div className="formula"><span>TÉCNICO {asset.score - asset.penalties.reduce((s,p)=>s+p.points,0)}</span><span>NOTICIAS {asset.penalties.find(p=>p.label.includes("Geopolitical"))?.points ?? 0}</span><b>FINAL {asset.score}</b></div><p className="disclaimer">Fecha: {new Date().toISOString()} · Fuente: Binance Spot · Entorno altseason: {alt ?? "no disponible"}/100. Niveles indicativos derivados del rango observado; validar antes de usar.</p></aside></div>;
}

export default function RadarApp() {
  const [data, setData] = useState<RadarPayload | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [tab, setTab] = useState("RESUMEN"); const [selected, setSelected] = useState<ScoredAsset | null>(null); const [sound, setSound] = useState(false); const [lastUpdate, setLastUpdate] = useState<Date | null>(null); const [installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null);
  const refresh = useCallback(async () => { const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try { const server=fetch("/api/radar",{cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();const j=await r.json() as RadarPayload;if(!j.market.length)throw new Error();return j});const direct=loadDirectMarket();const first=await Promise.any([direct,server]);setData(first);setLastUpdate(new Date());setError("");server.then(richer=>{setData(richer);setLastUpdate(new Date())}).catch(()=>undefined); } catch { setError("CONEXIÓN DE DATOS NO DISPONIBLE"); } finally { clearTimeout(timeout);setLoading(false); } }, []);
  useEffect(() => { const boot = setTimeout(refresh, 0); const id = setInterval(refresh, 30000); return () => { clearTimeout(boot); clearInterval(id); }; }, [refresh]);
  useEffect(()=>{const capture=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);
  const installApp=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)};
  const risk = useMemo(() => globalRisk(data?.news ?? []), [data]);
  const alt = useMemo(() => altseasonScore(data?.market ?? [], data?.dominance.btc ?? null, risk.score), [data, risk.score]);
  const scored = useMemo(() => scoreAssets(data?.market ?? [], risk.score, risk.killSwitch), [data, risk]);
  const rot = useMemo(() => rotation(data?.market ?? []), [data]);
  const active = scored.filter(a => a.signal !== "NO SIGNAL").slice(0, 3);
  if (loading) return <main className="loading"><div className="brain-loader"><i/><i/><i/></div><h1>ALT RADAR <b>PRO</b></h1><p>INICIANDO CEREBRO DE MERCADO</p></main>;
  if (!data) return <main className="loading"><h1>ALT RADAR <b>PRO</b></h1><p>{error}</p><button onClick={refresh}>REINTENTAR CONEXIÓN</button></main>;
  return <main>
    <header><div className="brand"><div className="brand-mark"><i/><i/><i/></div><div><b>ALT RADAR</b><span>PRO</span><small>INTELIGENCIA DE MERCADO CRIPTO</small></div></div><nav>{["RESUMEN","ESCÁNER","INTELIGENCIA","HISTORIAL"].map(t => <button key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>{t}</button>)}</nav><div className="system"><span className={error ? "offline" : "live"}>● {error ? "DEGRADADO" : "EN VIVO"}</span>{installPrompt&&<button className="install-app" onClick={installApp}>↓ INSTALAR</button>}<button aria-label="Activar sonido" onClick={() => setSound(!sound)}>{sound ? "◉" : "○"}</button><button aria-label="Actualizar" onClick={refresh}>↻</button></div></header>
    <MarketStrip data={data}/>
    <div className="shell">
      {risk.killSwitch && <div className="kill"><b>🔴 BLOQUEO GEOPOLÍTICO</b><span>NUEVAS OPERACIONES PAUSADAS</span><small>El riesgo global superó el umbral de seguridad. Las señales existentes muestran advertencia de evento.</small></div>}
      <section className="hero-grid">
        <article className="panel alt-panel"><div className="panel-head"><div><p className="eyebrow">CEREBRO DE MERCADO / RÉGIMEN</p><h2>Probabilidad de altseason</h2></div><span className="status-dot">● CALCULADO</span></div><div className="alt-main"><ScoreRing score={alt.final} label="AJUSTADO"/><div className="alt-state"><span>ESTADO ACTUAL</span><h3>{alt.state}</h3><p>{alt.final !== null && alt.final >= 41 ? "La amplitud de capital se expande más allá de BTC. La confirmación depende de liquidez y riesgo." : "El capital permanece concentrado. No hay confirmación amplia de altcoins."}</p><div className="score-audit"><span>TÉCNICO BRUTO <b>{alt.raw ?? "—"}</b></span><span>NOTICIAS / MACRO <b className="negative">{alt.adjustment}</b></span><span>FINAL <b>{alt.final ?? "—"}</b></span></div></div></div><div className="factor-bars">{alt.factors.slice(0,5).map(f => <div key={f.label}><span>{f.label}</span><i><b style={{width:`${f.points/22*100}%`}}/></i><em>+{Math.round(f.points)}</em></div>)}</div></article>
        <article className="panel risk-panel"><div className="panel-head"><div><p className="eyebrow">INTELIGENCIA GLOBAL</p><h2>Riesgo geopolítico</h2></div><span className={risk.killSwitch ? "badge critical" : "badge"}>{risk.level}</span></div><div className="risk-score"><b>{risk.score ?? "—"}</b><span>/100</span><SparkBars values={(data.news.length ? data.news.slice(0,9).map(n => n.risk - 50) : [0,0,0,0,0])}/></div><div className="risk-scale"><i/><i/><i/><i/><i/></div>{data.news[0] ? <a className="headline" href={data.news[0].url} target="_blank" rel="noreferrer"><span>{data.news[0].status}</span><b>{data.news[0].title}</b><small>{data.news[0].source} · RIESGO {data.news[0].risk}</small></a> : <div className="empty">NOTICIAS NO DISPONIBLES</div>}</article>
        <article className="panel rotation-panel"><div className="panel-head"><div><p className="eyebrow">FLUJO DE CAPITAL</p><h2>Radar de rotación</h2></div><span className="phase">FASE {rot.phase}</span></div><div className="flow">{rot.values.map((r,i) => <div key={r.label} className={r.label === rot.leader ? "leader" : ""}><span>{r.label}</span><b>{r.value}%</b>{i < 4 && <em>›</em>}</div>)}</div><p className="flow-caption">FASE ACTUAL DE ROTACIÓN</p><h3>BTC <span>→</span> ETH <span>→</span> {rot.leader.toUpperCase()}</h3><small>Inferido del rendimiento transversal de 24h. No representa flujos reales de fondos.</small></article>
      </section>
      <section className="signals-section"><div className="section-head"><div><p className="eyebrow">MOTOR DE CONFLUENCIA</p><h2>Inteligencia activa</h2></div><span>{active.length ? `${active.length} CONFIGURACIONES CALIFICADAS` : "SIN SEÑALES DE ALTA CONVICCIÓN"}</span></div>{active.length ? <div className="signal-cards">{active.map(a => <button className="signal-card" key={a.symbol} onClick={() => setSelected(a)}><div><span className={`signal-pill ${a.signal.toLowerCase()}`}>{a.signal}</span><small>{assetName(a.symbol)}/USDT · 15M/1H</small></div><strong>{a.score}<em>/100</em></strong><p>{a.reasons.filter(r=>r.points>=10).slice(0,4).map(r=><span key={r.label}>✓ {r.label}</span>)}</p><div><b>{pct(a.change24h)} <small>24H</small></b><b>{a.liquidity} <small>LIQUIDEZ</small></b><i>VER TRAZA →</i></div></button>)}</div> : <div className="no-signals"><div>◎</div><h3>SIN SEÑALES DE ALTA CONVICCIÓN</h3><p>El cerebro está monitoreando. No fabricará operaciones sin confirmaciones independientes.</p></div>}</section>
      <LiveBookmap symbols={data.market.map(a=>a.symbol)}/>
      <LiquidityMap symbols={data.market.map(a=>a.symbol)}/>
      <section className="lower-grid">
        <article className="panel scanner"><div className="panel-head"><div><p className="eyebrow">UNIVERSO LÍQUIDO</p><h2>Escáner pre-pump</h2></div><span className="muted">TOP {scored.length} · EN VIVO</span></div><div className="table-wrap"><table><thead><tr><th>ACTIVO</th><th>PRECIO</th><th>1H</th><th>4H</th><th>24H</th><th>VOL</th><th>MOMENTUM</th><th>SCORE</th><th>SEÑAL</th></tr></thead><tbody>{scored.slice(0,12).map(a => <tr key={a.symbol} onClick={() => setSelected(a)}><td><b>{assetName(a.symbol)}</b><small>/USDT</small></td><td>{fmtPrice(a.price)}</td><td className={(a.change1h??0)>=0?"positive":"negative"}>{pct(a.change1h)}</td><td className={(a.change4h??0)>=0?"positive":"negative"}>{pct(a.change4h)}</td><td className={a.change24h>=0?"positive":"negative"}>{pct(a.change24h)}</td><td>${compact(a.quoteVolume)}</td><td><SparkBars values={[a.change24h*.3,a.change4h??0,a.change1h??0,a.momentum]}/></td><td><div className="mini-score"><i style={{width:`${a.score}%`}}/><b>{a.score}</b></div></td><td><span className={`signal-pill ${a.signal.toLowerCase().replace(" ", "-")}`}>{a.extended ? "EXTENDIDO" : a.signal}</span></td></tr>)}</tbody></table></div></article>
        <article className="panel intelligence"><div className="panel-head"><div><p className="eyebrow">FLUJO DE EVENTOS CURADO</p><h2>Inteligencia global</h2></div><span className="badge">ALTO + CRÍTICO</span></div><div className="news-list">{data.news.slice(0,7).map(n => <a href={n.url} target="_blank" rel="noreferrer" key={n.id}><time>{new Date(n.publishedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><div><b>{n.title}</b><small>{n.region} · {n.source}</small></div><span className={n.risk > 70 ? "hot" : ""}>{n.risk}</span></a>)}{!data.news.length && <div className="empty">NOTICIAS GLOBALES NO DISPONIBLES</div>}</div></article>
      </section>
      <footer><div><b>ALT RADAR PRO</b><span>INTELIGENCIA DE DECISIÓN · NO EJECUCIÓN</span></div><p>Las señales son escenarios probabilísticos, no garantías ni asesoramiento financiero.</p><small>Actualizado {lastUpdate?.toLocaleTimeString() ?? "—"} · Fuentes: {data.sources.join(" · ") || "no disponibles"}</small></footer>
    </div>{selected && <SignalDrawer asset={selected} close={() => setSelected(null)} alt={alt.final}/>} 
  </main>;
}
